### ISSUE TITLE
Digiconomist  kWh data accuracy

### ISSUE THREAD

**Issue by sterlingcrispin** [kylemcdonald/ethereum-nft-activity#1]
I've brought this up elsewhere but I'd love your perspective. 

Since you're relying on Digiconomist energy estimation maybe you can help me get to the bottom of this: 

Digiconomist says they:
1. Calculate total USD Mining revenues
2. Estimate what part is spent on electricity
3. Find out how much miners pay per kWh
4. Convert costs to consumption

If you go to you can see their source of data https://digiconomist.net/ethereum-energy-consumption

However for those four steps:

1. There's no source for the mining revenue for Ethereum
2. There's no source for the how much of that revenue is spent on electricity 
3. There's no source for their estimate of "miners are assumed to be paying 10 cents per KWh on average" 
4. There's no source for how they get the kWh consumption, at the end of these layers of assumptions with no sources 

I think it's really problematic all these calculators like carbon.fyi, cryptoart.wtf and now yours are being built on top of these layers of assumptions and "energy assumed backwards from profit with no sources".

I've seen a handful of other Bitcoin studies that are more "bottom up" than "top down" like https://www.sciencedirect.com/science/article/pii/S2542435119302557 but their estimates are on the low end of Digiconomist and they say at length:

> Previous academic studies, such as predictions of future carbon emissions or comparisons of cryptocurrency and metal mining, are based on simplistic estimates of power consumption and lack empirical foundations. Consequently, the estimates produced vary significantly among studies

I don't think you should use Digiconomist as a source of data if they have no sources. If you can find a more rigorous estimate of Ethereum network energy usage I think it would be really a great resource. Digiconomist lacks credibility even though its so highly pointed to

**Comment by justincone** [comment]
I very much would like to hear Memo's response to this.

**Comment by kylemcdonald** [comment]
hi sterling :) energy use and emissions for bitcoin is certainly better studied than for ethereum.

when i reviewed this topic, i found one recurring sentiment: it is very important to tie crypto energy use to a date. koomey stresses this in his work. because cryptoart is a very recent phenomena, estimates from 2017-2019 cannot be used.

as far as i've been able to find so far, digiconomist is the only source that attempts to provide a continuous estimate across multiple dates. so it's the only source that meets a basic requirement that is agreed upon by all researchers.

i would absolutely love to see a bottom up estimate for ethereum emissions. i've seen some for bitcoin, but for ethereum it would be a bit more intensive since we are talking about GPU releases and not infrequent ASIC releases.

i would also add that regarding point 1, the mining revenue, this is easy to calculate based on the price of ethereum. the other points are indeed back-of-the-envelope assumptions.

personally, what i would like even more than a bottom-up time-continuous estimate is something that provides upper and lower bounds and confidence intervals. if you find any of these things, please drop them here. for now i'll keep working with what i've got!

**Comment by mattdesl** [comment]
I assume you have seen this already:

https://cbeci.org/

The methodology they present for lower bound makes sense to me. Choose the best mining device on the market, treat it like every miner is using it, and then apply that to the current network hash rate to understand GW. This can give you the lower bound, assuming all miners are using the best equipment.

Their method for calculating upper and best-guess estimates also seems reasonable, i.e. getting the average efficiency from the list of GPUs that are still profitable. Probably should be possible to apply to Eth, the hardest part is sourcing a list of mining GPUs I would think?

There is also this 2020 paper which was pointed to me by Sterling, it seems to have a fairly similar methodology, but includes a list of GPUs for mining Ethereum and their efficiencies.

https://www.cell.com/joule/pdfExtended/S2542-4351(20)30331-7

**Comment by kylemcdonald** [comment]
@mattdesl the CBECI approach is exactly what i want, but for ethereum! i have looked into the 2020 TUM paper and i think i might just get in contact with all the authors. hopefully carbon.fyi and offsetra can adopt this approach, and we can move towards a better model.

**Comment by kylemcdonald** [comment]
fwiw i'm rebuilding a model that is inspired by CBECI, but for ethereum. https://github.com/kylemcdonald/ethereum-energy

**Comment by mattdesl** [comment]
Thanks Kyle – just reading it, looks fantastic. 👏

**Comment by kylemcdonald** [comment]
Closing this issue as any Digiconomist references have been completely removed with my bottom-up emissions estimates, as of b6749798f357773f8ae50b39ffd55ab5a3be58e7
