### ISSUE TITLE
replace all kgco2_per_gas calculations with csv

### ISSUE THREAD

**Issue by kylemcdonald** [kylemcdonald/ethereum-nft-activity#5]
all of this should be replaced https://github.com/kylemcdonald/cryptoart-footprint/blob/main/ethereum_footprint.py#L20-L45 so we don't do the math every time we run.

not for efficiency's sake, but for simplicity.

update: working on new process for this in https://github.com/kylemcdonald/ethereum-energy/

**Comment by Carbontwin** [comment]
@kylemcdonald @pippinlee Hi, what do you think about voluntary carbon offseting ? In case of traditional industry corporations offseting CO2 in order  to reach carbon neutrality. Who shoul offset CP2 in case of crypto-market ?

**Comment by kylemcdonald** [comment]
> @kylemcdonald @pippinlee Hi, what do you think about voluntary carbon offseting ? In case of traditional industry corporations offseting CO2 in order to reach carbon neutrality. Who should offset CP2 in case of crypto-market ?

i believe in spending money on carbon removal and reduction. i don't believe that this expenditure excuses emissions.

cryptoart marketplaces should take responsibility for the infrastructure they have provided to artists, including the CO2 they have participated in emitting.

**Comment by Carbontwin** [comment]
it can be assumed that approximately 70% of each transaction in the network is powered  by energy from non-renewable sources, and accordingly should be offseted for  carbon dioxide emissions. Perhaps the best method is to mark the transactions on the network as green-not green and issue the corresponding NFT token. Our CORC carbon emission reduction certificate is exactly about this and is provided by the bank of carbon credits accumulated since 2008, certified in accordance with the rules of the Kyoto Protocol. Our several million tons of carbon credits are enough to offset the entire NFT token market

**Comment by kylemcdonald** [comment]
deleting off-topic discussion. please feel free to contact me [on twitter](https://twitter.com/kcimc) for general discussion.

**Comment by kylemcdonald** [comment]
Closed as of b6749798f357773f8ae50b39ffd55ab5a3be58e7
